"""add_payment_type_to_emission

Revision ID: a8f1c094a832
Revises: e84c35e4a387
Create Date: 2026-06-23 08:21:04.203873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f1c094a832'
down_revision: Union[str, Sequence[str], None] = 'e84c35e4a387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emission_orders', sa.Column('payment_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emission_orders', 'payment_type')
    # ### end Alembic commands ###
